# Generated by Django 2.2.6 on 2019-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quote_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
